#index:
#    path: /
#    controller: App\Controller\DefaultController::index

users:
  path: /api/users
  controller: App\Controller\UserController::getUsers

register:
  path: /api/register
  controller: App\Controller\RegistrationController::register

login:
  path: /api/login
  controller: App\Controller\SecurityController::login